---
- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present
  when: "{{ ansible_pkg_mgr == 'yum' and not ansible_selinux }}"

- name: Create wheel group
  group: name=wheel state=present

- name: wheel sudoers
  copy: content="%wheel        ALL=(ALL) NOPASSWD{{':'}} ALL\n" dest=/etc/sudoers.d/wheel-nopasswd
            owner=root
            group=root
            mode=0440

- name: "Users: create"
  user: name="{{ lookup('env', 'USER') }}" shell=/bin/bash groups=wheel append=yes

- name: "Users: put keys"
  authorized_key: user="{{ lookup('env', 'USER') }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub' ) }}" state=present

- name: show ip addresses
  debug: var=ansible_all_ipv4_addresses
